# Continuous Integration: lint, type-check, and tests across Python versions and OSes
name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-test:
    name: Lint, Type, Test (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Dev/tooling deps from pyproject optional-dependencies
          pip install .[dev]

      - name: Ruff (lint)
        run: ruff check .

      - name: Mypy (type-check)
        run: mypy mJiraWorkLogExtractor.py src/jira_worklog_extractor

      - name: Run tests
        run: pytest -q
