# Build Windows EXE with PyInstaller on version tags and upload as artifact
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows-exe:
    name: Build Windows EXE (PyInstaller)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          # Optional Windows trust store integration for the builder:
          # pip install certifi-win32

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --onefile --name mJiraWorkLogExtractor --icon mJiraWorkLogExtractor.ico --hidden-import dateutil.relativedelta mJiraWorkLogExtractor.py
          echo "Listing dist directory contents:"
          Get-ChildItem dist

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: mJiraWorkLogExtractor-${{ github.ref_name }}-windows
          path: dist/mJiraWorkLogExtractor.exe
          if-no-files-found: error
